"""Init

Revision ID: 0128ad12f22c
Revises: cea401a7b5e4
Create Date: 2022-07-20 16:05:21.779503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0128ad12f22c'
down_revision = 'cea401a7b5e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('created', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'created')
    # ### end Alembic commands ###
