# Generated by Django 4.1 on 2022-08-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('plan_plus', models.CharField(max_length=50, verbose_name='Плановые нормальные доходы')),
                ('unplan_plus', models.CharField(max_length=50, verbose_name='Внелановые нормальные доходы')),
                ('fart_plus', models.CharField(max_length=50, verbose_name='Случайные доходы')),
                ('plan_minus', models.CharField(max_length=50, verbose_name='Плановые нормальные расходы')),
                ('unplan_minus', models.CharField(max_length=50, verbose_name='Внеплановые нормальные расходы')),
                ('idiotic_minus', models.CharField(max_length=50, verbose_name='Идиотские расходы')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
            ],
        ),
    ]
